export const movieTitles = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "Pulp Fiction",
  "The Lord of the Rings: The Return of the King",
  "Forrest Gump",
  "Inception",
  "The Matrix",
  "Goodfellas",
  "Fight Club",
  "The Empire Strikes Back",
  "The Godfather: Part II",
  "The Silence of the Lambs",
  "City of God",
  "Schindler's List",
  "Seven Samurai",
  "The Usual Suspects",
  "Life is Beautiful",
  "Spirited Away",
  "Saving Private Ryan",
  "Interstellar",
  "The Green Mile",
  "The Prestige",
  "Parasite",
  "The Lion King",
  "Gladiator",
  "Whiplash",
  "Back to the Future",
  "The Departed",
  "The Terminator",
  "The Great Dictator",
  "The Dark Knight Rises",
  "Jaws",
  "The Shining",
  "The Pianist",
  "The Good, the Bad and the Ugly",
  "The Lion King",
  "Casablanca",
  "The Breakfast Club",
  "The Big Lebowski",
  "12 Angry Men",
  "The Fugitive",
  "A Clockwork Orange",
  "American History X",
  "Memento",
  "The Social Network",
  "The Truman Show",
  "Good Will Hunting",
  "The Revenant",
  "One Flew Over the Cuckoo's Nest",
  "Inglourious Basterds",
  "Terminator 2: Judgment Day",
  "The Matrix Reloaded",
  "A Beautiful Mind",
  "The Wolf of Wall Street",
  "Batman Begins",
  "Spider-Man: Into the Spider-Verse",
  "Star Wars: A New Hope",
  "The Incredibles",
  "The Avengers",
  "Titanic",
  "The Grand Budapest Hotel",
  "Amélie",
  "Deadpool",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Big Short",
  "The Hunger Games",
  "The Godfather Part III",
  "Mad Max: Fury Road",
  "Guardians of the Galaxy",
  "Star Wars: The Force Awakens",
  "The Witch",
  "Your Name",
  "The Shape of Water",
  "The Hateful Eight",
  "Jurassic Park",
  "The Dark Knight Returns",
  "The Exorcist",
  "The Secret Life of Walter Mitty",
  "The Grandmaster",
  "The Hurt Locker",
  "The Godfather: Part II",
  "Requiem for a Dream",
  "Moonlight",
  "Drive",
  "Eternal Sunshine of the Spotless Mind",
  "The Lego Movie",
  "King Kong",
  "Pulp Fiction",
  "Blade Runner 2049",
  "Her",
  "The Martian",
  "The Secret Garden",
  "The Croods",
  "Gravity",
  "Django Unchained",
  "Inception",
  "Slumdog Millionaire",
  "Fargo",
  "The Lion King 2",
  "Toy Story",
  "The Good Place",
  "The Secret Life of Bees",
  "The Outsiders",
  "Howl's Moving Castle",
  "A Star is Born",
  "Into the Wild",
  "Coco",
  "Big Fish",
  "Singin' in the Rain"
];
